// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: matching/v1/matching.proto

package matchingv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/shwatanap/connect-tic-tac-toe/src/api/matching/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// MatchingServiceName is the fully-qualified name of the MatchingService service.
	MatchingServiceName = "matching.v1.MatchingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MatchingServiceJoinRoomProcedure is the fully-qualified name of the MatchingService's JoinRoom
	// RPC.
	MatchingServiceJoinRoomProcedure = "/matching.v1.MatchingService/JoinRoom"
)

// MatchingServiceClient is a client for the matching.v1.MatchingService service.
type MatchingServiceClient interface {
	JoinRoom(context.Context, *connect_go.Request[v1.JoinRoomRequest]) (*connect_go.ServerStreamForClient[v1.JoinRoomResponse], error)
}

// NewMatchingServiceClient constructs a client for the matching.v1.MatchingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMatchingServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) MatchingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &matchingServiceClient{
		joinRoom: connect_go.NewClient[v1.JoinRoomRequest, v1.JoinRoomResponse](
			httpClient,
			baseURL+MatchingServiceJoinRoomProcedure,
			opts...,
		),
	}
}

// matchingServiceClient implements MatchingServiceClient.
type matchingServiceClient struct {
	joinRoom *connect_go.Client[v1.JoinRoomRequest, v1.JoinRoomResponse]
}

// JoinRoom calls matching.v1.MatchingService.JoinRoom.
func (c *matchingServiceClient) JoinRoom(ctx context.Context, req *connect_go.Request[v1.JoinRoomRequest]) (*connect_go.ServerStreamForClient[v1.JoinRoomResponse], error) {
	return c.joinRoom.CallServerStream(ctx, req)
}

// MatchingServiceHandler is an implementation of the matching.v1.MatchingService service.
type MatchingServiceHandler interface {
	JoinRoom(context.Context, *connect_go.Request[v1.JoinRoomRequest], *connect_go.ServerStream[v1.JoinRoomResponse]) error
}

// NewMatchingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMatchingServiceHandler(svc MatchingServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	matchingServiceJoinRoomHandler := connect_go.NewServerStreamHandler(
		MatchingServiceJoinRoomProcedure,
		svc.JoinRoom,
		opts...,
	)
	return "/matching.v1.MatchingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MatchingServiceJoinRoomProcedure:
			matchingServiceJoinRoomHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMatchingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMatchingServiceHandler struct{}

func (UnimplementedMatchingServiceHandler) JoinRoom(context.Context, *connect_go.Request[v1.JoinRoomRequest], *connect_go.ServerStream[v1.JoinRoomResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("matching.v1.MatchingService.JoinRoom is not implemented"))
}
